apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  rules:
#    - host: shopping.com
      http:
        paths:
          - path: /
            backend:
              serviceName: converter-pdf
              servicePort: 8080